
import type { Document, ExtractedImage, ExtractedTable } from '../types/types';
import { DocumentStatus } from '../types/types';

const MOCK_PROCESSING_STEPS = [
  { message: "Initializing analysis...", delay: 1000 },
  { message: "Extracting text content...", delay: 1500 },
  { message: "Detecting images...", delay: 1000 },
  { message: "Performing OCR on 3 images...", delay: 2500 },
  { message: "Reconstructing 2 tables...", delay: 1500 },
  { message: "Generating Markdown output...", delay: 1000 },
  { message: "Finalizing document...", delay: 500 },
];

const createMockData = (doc: Document): Document => {
  const images: ExtractedImage[] = [
    { id: 'img1', url: 'https://picsum.photos/seed/pdf-image-1/800/600', ocrText: 'A landscape with mountains and a lake.', caption: 'Fig. 1: Mountain Vista' },
    { id: 'img2', url: 'https://picsum.photos/seed/pdf-image-2/800/400', ocrText: 'A chart showing upward trends.', caption: 'Fig. 2: Q3 Growth Chart' },
    { id: 'img3', url: 'https://picsum.photos/seed/pdf-image-3/600/600', ocrText: 'A city skyline at night.', caption: 'Fig. 3: Urban Nightscape' },
  ];

  const tables: ExtractedTable[] = [
    {
      id: 'tbl1',
      rows: 3,
      columns: 3,
      caption: 'Table 1: Quarterly Sales Figures',
      markdown: `| Region  | Q1 Sales | Q2 Sales |\n|---------|----------|----------|\n| North   | $150,000 | $170,000 |\n| South   | $120,000 | $135,000 |\n| East    | $180,000 | $195,000 |`
    },
    {
      id: 'tbl2',
      rows: 4,
      columns: 2,
      caption: 'Table 2: Project Milestones',
      markdown: `| Milestone            | Completion Date |\n|----------------------|-----------------|\n| Project Kick-off     | 2023-01-15      |\n| Design Phase       | 2023-03-01      |\n| Development Sprint 1 | 2023-04-15      |\n| Final Release        | 2023-06-01      |`
    },
  ];

  const markdownContent = `
# Analysis Report: ${doc.fileName}

This document was automatically generated by PDFusion.

## Section 1: Introduction

This section contains the primary text extracted from the document. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.

### Subsection 1.1: Key Findings

- **Finding A:** The data indicates a positive trend.
- **Finding B:** Further analysis is required for conclusive results.
- **Finding C:** Market share has increased by 5%.

Here is the first image extracted from the document:

![${images[0].caption}](${images[0].url})
*${images[0].caption}*

## Section 2: Data & Tables

The following tables were extracted and reconstructed from the PDF.

${tables[0].markdown}
*${tables[0].caption}*

---

${tables[1].markdown}
*${tables[1].caption}*

## Section 3: Visual Content

Additional images found in the document are displayed below.

![${images[1].caption}](${images[1].url})
*${images[1].caption}*

![${images[2].caption}](${images[2].url})
*${images[2].caption}*

## Section 4: Conclusion

The analysis is complete. This Markdown provides a structured overview of the original PDF content.
  `;

  return {
    ...doc,
    status: DocumentStatus.COMPLETED,
    markdownContent,
    extractedImages: images,
    extractedTables: tables,
  };
};


export const processDocument = (
  doc: Document,
  onProgress: (message: string) => void
): Promise<Document> => {
  return new Promise((resolve, reject) => {
    let currentStep = 0;
    
    const executeStep = () => {
      if (currentStep < MOCK_PROCESSING_STEPS.length) {
        const step = MOCK_PROCESSING_STEPS[currentStep];
        onProgress(step.message);
        setTimeout(() => {
          currentStep++;
          executeStep();
        }, step.delay);
      } else {
        // Simulate a small chance of failure for demonstration
        if (Math.random() > 0.9) {
          const errorDoc = { ...doc, status: DocumentStatus.FAILED, errorMessage: 'Failed during OCR processing due to low image quality.' };
          reject(errorDoc);
        } else {
          const completedDoc = createMockData(doc);
          resolve(completedDoc);
        }
      }
    };
    
    onProgress('Upload complete. Starting processing...');
    setTimeout(executeStep, 500);
  });
};
